language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

cache:
  directories:
    - vendor

before_script:
  - composer self-update --clean-backups
  - composer install --dev --no-interaction --prefer-source --optimize-autoloader

script:
  - vendor/bin/phpunit
