language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

notifications:
  email:
    - sam.james.parkinson@gmail.com

before_script:
  - composer install --dev --no-interaction --prefer-source --optimize-autoloader
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit
