language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

sudo: false

install:
  - travis_retry composer install --no-interaction

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - composer run-script test
