language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source --optimize-autoloader

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
