language: php

sudo: false

php:
- 5.5
- 5.6
- 7.0
- hhvm
- hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor/

install:
  - travis_retry composer install --no-interaction

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - composer test --quiet
