language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  global:
    - secure: "alM2WV/Izn08ffFO+nOvmrYbth/uPpvBdq2wjsUngGSM0hKXKFOWcEQwNxVxdj+9Y+Qisc28X1Ok1hFKKunzm5KMfsPSZ8NX5bLyDNUFy4aqoLSuvy8fNGyyz7ue8XnMMIinjooFEzUhQRG3bpyI2R2xyBKBeOMud6SQL4mIEtY="

notifications:
  email:
    - sam.james.parkinson@gmail.com

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source --optimize-autoloader
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_success:
  - vendor/bin/test-reporter
