language: php

sudo: false

php:
- 5.5
- 5.6
- hhvm
- hhvm-nightly

cache:
  directories:
    - vendor/

install:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - travis_retry composer install --no-interaction

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - composer run-script test --quiet

env:
  global:
    secure: CJTrLsEvCAmZw8J2kEEFHhXfHJyV5iJ3JKI/A8R7FGw9MhdLoliiqt6dtdbxyvq9+yCRAjq2SRJof+pDOPoOxIAjpfSpEh+FI/vTIrQM0otIR+9LFr4B7uirCrYc5D02TvIpEzLLEKVq60IXUFIcV+LAcl10uBQ0PE7GlE4vRs4=
