language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  global:
    - secure: "alM2WV/Izn08ffFO+nOvmrYbth/uPpvBdq2wjsUngGSM0hKXKFOWcEQwNxVxdj+9Y+Qisc28X1Ok1hFKKunzm5KMfsPSZ8NX5bLyDNUFy4aqoLSuvy8fNGyyz7ue8XnMMIinjooFEzUhQRG3bpyI2R2xyBKBeOMud6SQL4mIEtY="

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source --optimize-autoloader

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-clover build/logs/clover.xml tests
  - ./vendor/bin/test-reporter

notifications:
  email:
    - sam.james.parkinson@gmail.com
