language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

addons:
  code_climate:
    repo_token: db3a9d5167930c783c659b6a713719a2f4b7fac416d579c024fbfce876c30c11

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source --optimize-autoloader
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter
