language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source --optimize-autoloader

script:
  - vendor/bin/phpunit
