language: php

sudo: false

php:
- 5.5
- 5.6
- 7.0
- hhvm

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - composer test --quiet
