language: php

sudo: false

php:
- 5.5
- 5.6
- hhvm
- hhvm-nightly

cache:
  directories:
    - vendor/

install:
  - composer config --global --quiet github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - travis_retry composer install --no-interaction

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - composer run-script test --quiet

env:
  global:
    secure: VYF/uhA4KZyaXAzjZCtPpeRq2G/SJZMKBeZG/mru8pZk5sPIWaZZGwu/hnKme7EcsK6ESB5P2fXUBJ2LjEi8JlxWqQ71aSNOY+X06d8xM9LOwnHvAAHo1HvS5H+UukvhGhtU6dK9Lq4w1WyZ9bDUY3QszmqL25lIx7JKkhgWIzg=
