language: php

sudo: false

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

cache:
  directories:
    - vendor/

install:
  - travis_retry composer install --no-interaction

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - composer run-script test
