language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

cache:
  directories:
    - vendor/

before_script:
  - composer self-update
  - composer install --no-interaction --optimize-autoloader

script:
  - vendor/bin/phpunit
