language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

install:
  - travis_retry composer install --no-interaction --optimize-autoloader --prefer-source

script:
  - vendor/bin/phpunit --exclude-group excludeFromTravis
  - vendor/bin/php-cs-fixer fix --dry-run --verbose
